### ISSUE TITLE
Undo Issues :vim:

### ISSUE THREAD

**Issue by tami5** [eraserhd/parinfer-rust#93] opened 2020-12-07 14:48 UTC
Hey @eraserhd, I lost the ability to undo and redo.  Basically when I edit and want to undo, I can undo two steps then the undo history becomes blank, pressing u u u go back in history but empty. Then when I try to redo it tells me `Already at newest change.`

Thanks

**Comment by hissssst** [comment] 2021-01-26 14:11
I am experiencing exactly the same issue

**Comment by bhurlow** [comment] 2021-03-18 01:48
seeing same

**Comment by eraserhd** [comment] 2021-04-30 13:33
Closing, as this is definitely a duplicate of #14.

**Closed by eraserhd** 2021-04-30 13:33 UTC

**Comment by eraserhd** [comment] 2021-04-30 14:51
After closer inspection, this is a separate issue.   I can't reproduce on Vim 8.2.1522, but I have suspicions about what is happening.  Next time it happens, can you post VIm/Neovim, version, starting buffer contents and keystrokes to reproduce?

**Comment by agorgl** [comment] 2022-08-11 15:59
Seeing the same issue in current neovim!
