### ISSUE TITLE
Undo not working properly in Vim8 and Neovim

### ISSUE THREAD

**Issue by spinningarrow** [eraserhd/parinfer-rust#14] opened 2018-04-07 05:10 UTC
I just installed this plugin; I'm using Vim 8.0 on macOS with patches: 1-1650 included. I'm seeing some odd behaviour when I undo. Let's say I have the following text in the buffer:

```clojure
(defn f
  [x]
  x)

(defn g
  [y]
  y)
```

I go to line 4, press `O` followed by `Enter` and insert another function so that my buffer looks like this:

```clojure
(defn f
  [x]
  x)

(defn h
  [z]
  z)

(defn g
  [y]
  y)
```

Now when I press `u` to undo, I get:

```clojure
(defn f
  [x]
  x
  []
  z)

(defn g
  [y]
  y)
```

whereas I would have expected something like the buffer in the first example above. Pressing `u` more times doesn't help - it keeps going through what appears to be a very long changelist but with no change being made to the buffer.

**Comment by daveyarwood** [comment] 2018-05-18 01:31
FWIW, I'm seeing similar undo issues in Neovim on Ubuntu 16.04.

**Comment by spinningarrow** [comment] 2018-05-21 15:38
@daveyarwood Thanks for the report! I've updated the issue title to reflect that.

**Comment by barkanido** [comment] 2018-06-28 10:40
same here on neovim + vimR on osX

**Comment by jeaye** [comment] 2018-08-02 00:35
Also seeing this on NeoVim v0.3.1 on Arch. @eraserhd, any update on it?

**Comment by spinningarrow** [comment] 2018-08-02 00:43
I’ve been looking into it in and off since it’s the same issue as https://github.com/bhurlow/vim-parinfer/issues/48; I’ve had no luck so far 😔

**Comment by jeaye** [comment] 2018-08-02 00:46
Thanks for the update, @spinningarrow. Looks like I'll remove Parinfer for now, until it's better integrated with Vim. Not an easy problem, this one; trying to bend Vim into unfamiliar shapes can be a harrowing experience.

**Comment by eraserhd** [comment] 2018-08-07 00:08
I've narrowed this down to a small case and found that it is a Vim bug and reported it: vim/vim#3291

**Comment by eraserhd** [comment] 2018-08-08 17:54
Current status is: Vim made a fix in patch 8.1.245 for the bug that I've reported, but it doesn't help us, really.  In fact, it likely makes what we want to do harder.  So I'm discussing with Bram how to proceed.

Hopefully, we'll make `undojoin` work in insert mode (which it doesn't currently because insert mode is weird).  This might be a lot of work, but I'm going to investigate doing it.  If I can't, then I'll just disable parinfer around `u` and `<C-R>`.  Alternately, I can try to handle LeaveInsert and undo back to the start insert point and replay the buffer changes as one change.  I've played around with these options and not had much luck, but we'll see.

**Comment by eraserhd** [comment] 2018-08-08 22:01
🎉  Vim 8.1.256 makes undo Just Work(tm)!

I'm going to leave this ticket open until this gets merged into Neovim and both are versions that Homebrew installs by default.

**Comment by eraserhd** [comment] 2018-08-09 00:00
@jeaye I just submitted the above-referenced PR to Neovim, which fixes it by bringing in the two Vim fixes.  Neovim seems to be behind a bit, and only a few patches from Vim 8.1 have made it in.  Not sure why.

**Comment by eraserhd** [comment] 2018-08-14 14:40
Neovim has merged 8832 and slated it for the next release!

**Comment by hukka** [comment] 2019-02-18 11:11
@eraserhd It seems like neovim has included the fixes for a while too, so this could be closed for good.

**Comment by eraserhd** [comment] 2019-02-18 13:44
@hukka thanks for the reminder

**Comment by knubie** [comment] 2019-08-04 15:07
I'm not sure if this is the same issue, but I'm experiencing an issue where undo will just stop undoing after a couple of undos. It's difficult to give reproduction steps because it sort of happens randomly.

Using Neovim 0.3.7

**Comment by TimoKramer** [comment] 2020-07-28 11:36
this should be reopened. the exact same problem is still there.

**Comment by eraserhd** [comment] 2020-08-03 14:45
Since this appears to be happening again, perhaps the fix got reverted.  If that's the case, we should figure out why by doing a `git bisect` on the Vim repo to find the commit.

**Comment by TimoKramer** [comment] 2020-08-25 12:13
sorry, I don't know C or Rust and I can not help with that problem. will try to help with stuff in the future since this plugin is really highly appreciated!

**Comment by xlfe** [comment] 2021-01-04 07:10
I'm having this problem too.

@eraserhd just trying to see which of your changes have since been modified.

Would this one be a problem?

https://github.com/neovim/neovim/commit/cf9887c838d6b38648d25bb82d6ee569549a5c63


see - 
https://github.com/neovim/neovim/blame/a1ed941a7881122fda2fd48e71e890ed55e4d08e/src/nvim/edit.c#L9168

**Comment by hissssst** [comment] 2021-01-26 14:12
Came here from #93. Is it duplicate?

**Comment by eraserhd** [comment] 2021-04-30 14:46
I'm on Vim 8.2.1522, and the original test case is working for me.  I'm sure there _are_ undo problems on Vim, but I'm closing this again, since I can't reproduce.  If you encounter issues, please start a new issue with a reproducible (bonus points for small) test case.

**Closed by eraserhd** 2021-04-30 14:46 UTC
